env:
  global:
    - CC_TEST_REPORTER_ID=4eed0d135b9e1a1668a68e5e29cc71faf872937d13c42efa4faf42dad5ed3375

language: php

matrix:
  fast_finish: true
  include:
    - php: 5.6
      dist: xenial
      env:
        - analysis=no
        - coverage=no
        - phpunitflags="--stop-on-failure --exclude-group=live"
        - lint="php-cs-fixer"
    - php: 7.0
      dist: xenial
      env:
        - analysis=no
        - coverage=no
        - phpunitflags="--stop-on-failure --exclude-group=live"
    - php: 7.1
      dist: xenial
      env:
        - analysis=no
        - coverage=no
        - phpunitflags="--stop-on-failure --exclude-group=live"
    - php: 7.2
      dist: xenial
      env:
        - analysis=no
        - coverage=no
        - phpunitflags="--stop-on-failure --exclude-group=live"
    - php: 7.3
      dist: xenial
      env:
        - analysis=no
        - coverage=no
        - phpunitflags="--stop-on-failure --exclude-group=live"
    - php: 7.4
      dist: bionic
      env:
        - analysis=yes
        - coverage=yes
        - phpunitflags="--stop-on-failure --coverage-clover=clover.xml"

cache:
  directories:
    - ./vendor
    - ./psalm/cache

before_script:
  - if [[ "$coverage" = "no" ]]; then phpenv config-rm xdebug.ini; fi
  - composer install --no-interaction
  - if [[ "$coverage" = "yes" ]]; then curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter; fi
  - if [[ "$coverage" = "yes" ]]; then chmod +x ./cc-test-reporter; fi
  - if [[ "$coverage" = "yes" ]]; then ./cc-test-reporter before-build; fi
  - if [[ "$analysis" = "yes" ]]; then composer require --dev paragonie/hidden-string; fi
  - if [[ "$analysis" = "yes" ]]; then composer require --dev --update-with-dependencies "phpunit/phpunit:<9" vimeo/psalm psalm/plugin-phpunit maglnet/composer-require-checker:^2.0; fi

script:
  - vendor/bin/parallel-lint .php_cs.dist src tests examples
  - vendor/bin/phpunit $phpunitflags
  - if [[ "$analysis" = "yes" ]]; then vendor/bin/composer-require-checker check ./composer.json; fi
  - if [[ "$analysis" = "yes" ]]; then vendor/bin/psalm --show-info=false --shepherd; fi
  - if [[ "$lint" = "php-cs-fixer" ]]; then vendor/bin/php-cs-fixer fix --allow-risky=yes --no-interaction --dry-run --diff-format=udiff -v; fi

after_script:
  - if [[ "$coverage" = "yes" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT -t clover; fi
