env:
  global:
    - CC_TEST_REPORTER_ID=4eed0d135b9e1a1668a68e5e29cc71faf872937d13c42efa4faf42dad5ed3375

language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4snapshot

before_script:
  - composer install --no-interaction
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - curl https://cs.symfony.com/download/php-cs-fixer-v2.phar -o php-cs-fixer.phar
  - chmod +x php-cs-fixer.phar

script:
  - vendor/bin/phpunit
  - ./php-cs-fixer.phar fix --allow-risky=yes --no-interaction --dry-run --diff -v

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
